//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.21 at 12:16:54 AM EET 
//


package ee.taltech.cs.mbt.tdl.uppaal.tdl_parser.xml.parsing.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ee.taltech.cs.mbt.tdl.uppaal.tdl_parser.xml.parsing.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ee.taltech.cs.mbt.tdl.uppaal.tdl_parser.xml.parsing.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nta }
     * 
     */
    public Nta createNta() {
        return new Nta();
    }

    /**
     * Create an instance of {@link TemplateType }
     * 
     */
    public TemplateType createTemplateType() {
        return new TemplateType();
    }

    /**
     * Create an instance of {@link ParametersType }
     * 
     */
    public ParametersType createParametersType() {
        return new ParametersType();
    }

    /**
     * Create an instance of {@link InitType }
     * 
     */
    public InitType createInitType() {
        return new InitType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link EmptyType }
     * 
     */
    public EmptyType createEmptyType() {
        return new EmptyType();
    }

    /**
     * Create an instance of {@link TransitionType }
     * 
     */
    public TransitionType createTransitionType() {
        return new TransitionType();
    }

    /**
     * Create an instance of {@link IdRefType }
     * 
     */
    public IdRefType createIdRefType() {
        return new IdRefType();
    }

    /**
     * Create an instance of {@link LocationLabelType }
     * 
     */
    public LocationLabelType createLocationLabelType() {
        return new LocationLabelType();
    }

    /**
     * Create an instance of {@link TransitionLabelType }
     * 
     */
    public TransitionLabelType createTransitionLabelType() {
        return new TransitionLabelType();
    }

    /**
     * Create an instance of {@link NailType }
     * 
     */
    public NailType createNailType() {
        return new NailType();
    }

}
